import React from 'react'
import Head from 'next/head'
import Layout from '../container/Layout'
import About from '../component/Home/About'
import Services from '../component/Home/Services'
import Founders from '../component/Home/Founders'

const Home = () => {
  return (
    <>
      <Head>
        <title>watch-shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Layout>
          <About />
          <Services />
          <Founders />
        </Layout>
      </main>
    </>
  )
}
export default Home
